/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import jmk.*;

public class _create_0table__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String table = request.getParameter("table");
int number = 1;
// try to get the number of fields, if format error, use default 1
try{
number = Integer.parseInt(request.getParameter("number"));
}catch(NumberFormatException nfe){}

if (table == null || table.trim() == ""){

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( session.getAttribute("db") ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      

}else{
    // check the table is here or not
    boolean createTable = false;
    ConDB dbcon = (ConDB)session.getAttribute("dbcon");
    Connection conn = dbcon.get();

    String sql = "desc " + table;
    PreparedStatement pstm = null;
    ResultSet rs = null;
   try{    
        pstm = conn.prepareStatement(sql);
        rs = pstm.executeQuery();
    }catch(Exception e){
        createTable = true;
    }

    // if table is not here, let it go
    if(createTable){

      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( table ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
 for (int i=0; i < number; i++){

      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( (i&1) ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( i ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( i ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( i ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( i ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      
}

      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( table ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( number ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      
    }else{
        // if table existed, error message
        out.println("Table is already existed! Please use another name. <br/>");
        out.println("<a href='create_table.jsp'>Back</a>");
    }
}

      out.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_create_0table__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/create_table.jsp", 12, 30);
    _caucho_line_map.add(27, 41);
    _caucho_line_map.add(41, 43);
    _caucho_line_map.add(62, 65);
    _caucho_line_map.add(78, 67);
    _caucho_line_map.add(81, 71);
    _caucho_line_map.add(122, 73);
    _caucho_line_map.add(123, 75);
    _caucho_line_map.add(124, 77);
    _caucho_line_map.add(125, 79);
    _caucho_line_map.add(131, 85);
    _caucho_line_map.add(132, 87);
    _caucho_line_map.add(150, 89);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/create_table.jsp"), "GqtoAjJ2C2BQPhWcm4bQfA==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string1;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  private final static char []_jsp_string4;
  private final static char []_jsp_string11;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string12;
  static {
    _jsp_string1 = "\n\n<h2>Create Table</h2>\n<hr/>\n<form method=\"post\">\n<table>\n    <tr> Create table on database ".toCharArray();
    _jsp_string10 = "\"></td>\n  </tr>\n".toCharArray();
    _jsp_string5 = "\n  <tr class=\"tb_row_".toCharArray();
    _jsp_string9 = "\"></td>\n    <td><input type=\"radio\" value=\"NA\" checked name=\"key_".toCharArray();
    _jsp_string6 = "\">\n    <td ><input type=\"text\" name=\"field[]\" size=\"16\"></td>\n    <td ><select size=\"1\" name=\"data_type[]\">\n    <option selected value=\"VARCHAR\">VARCHAR</option>\n    <option value=\"TEXT\">TEXT</option>\n    <option value=\"DATE\">DATE</option>\n    <option value=\"SMALLINT\">SMALLINT</option>\n    <option value=\"MEDIUMINT\">MEDIUMINT</option>\n    <option value=\"INT\">INT</option>\n    <option value=\"BIGINT\">BIGINT</option>\n    <option value=\"DOUBLE\">DOUBLE</option>\n    <option value=\"DECIMAL\">DECIMAL</option>\n    <option value=\"DATETIME\">DATETIME</option>\n    <option value=\"TIMESTAMP\">TIMESTAMP</option>\n    <option value=\"TIME\">TIME</option>\n    <option value=\"YEAR\">YEAR</option>\n    <option value=\"CHAR\">CHAR</option>\n    <option value=\"TINYBLOB\">TINYBLOB</option>\n    <option value=\"TINYTEXT\">TINYTEXT</option>\n    <option value=\"BLOB\">BLOB</option>\n    <option value=\"MEDIUMBLOB\">MEDIUMBLOB</option>\n    <option value=\"MEDIUMTEXT\">MEDIUMTEXT</option>\n    <option value=\"LONGBOLB\">LONGBOLB</option>\n    <option value=\"LONGTEXT\">LONGTEXT</option>\n    <option value=\"ENUM\">ENUM</option>\n    <option value=\"SET\">SET</option>\n    <option value=\"FLOAT\">FLOAT</option>\n    <option value=\"TINYINT\">TINYINT</option>\n    </select></td>\n    <td ><input type=\"text\" name=\"data_length[]\" size=\"5\"></td>\n    <td ><select size=\"1\" name=\"null_value[]\">\n    <option selected value=\"NOT NULL\">not null</option>\n    <option value=\"NULL\">null</option>\n    </select></td>\n    <td ><input type=\"text\" name=\"default_value[]\" size=\"10\"></td>\n    \n    <td ><select size=\"1\" name=\"extra[]\">\n    <option selected value=\"\"></option>\n    <option value=\"AUTO_INCREMENT\">AUTO_INCREMENT</option>\n    </select>\n    \n    <td ><input type=\"radio\" value=\"PRIMARY\" name=\"key_".toCharArray();
    _jsp_string8 = "\"></td>\n    <td ><input type=\"radio\" value=\"UNIQUE\" name=\"key_".toCharArray();
    _jsp_string7 = "\"></td>\n    <td ><input type=\"radio\" value=\"INDEX\" name=\"key_".toCharArray();
    _jsp_string13 = "\" />\n<br/><br/>\n<input type=\"hidden\" name=\"type\" value=\"create_table\" />\n<input type=\"submit\" value=\"Create\" />\n</form>\n\n<table border=\"0\" width=\"100%\">\n<tr><td>\n*  If field type is \"enum\" or \"set\", please enter the values using this format: 'a','b','c'...\n</td></tr>\n<tr><td>\nIf you ever need to put a backslash (\"\\\") or a single quote (\"'\") amongst those values, backslashes it (for example '\\\\xyz' or 'a\\'b').  \n</td></tr>\n<tr><td>\n**  For default values, please enter just a single value, without backslash escaping or quotes, using this format: a  \n</td></tr>\n</table>\n\n".toCharArray();
    _jsp_string14 = "\n</body>\n</html>\n".toCharArray();
    _jsp_string4 = "</b></h2>\n<hr/>\n<form action=\"run_sql.jsp\" method=\"post\">\n<table border=\"0\" width=\"100%\">\n  <tr class=\"tb_header\">\n    <td >Field Name</td>\n    <td >Type</td>\n    <td >Length</td>\n    <td >Null</td>\n    <td >Default</td>\n    <td >Extra</td>\n    <td >Primary</td>\n    <td >Index</td>\n    <td >Unique</td>\n    <td>---</td>\n  </tr>\n ".toCharArray();
    _jsp_string11 = "\n</table>\n<input type=\"hidden\" name=\"table\" value=\"".toCharArray();
    _jsp_string0 = "\n\n\n\n<html>\n<head><title>Create Table</title></head>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n<body>\n".toCharArray();
    _jsp_string3 = "\n<h2>Create Table <b style=\"color:blue\">".toCharArray();
    _jsp_string2 = " : </tr>\n    <tr>\n        <td>Table Name : </td>\n        <td><input type=\"text\" name=\"table\"/></td>\n    </tr>\n    <tr>\n        <td>Fields : </td>\n        <td>\n            <input type=\"text\" name=\"number\" size=\"5\"/>\n            <input type=\"submit\" value=\"Create\">\n        </td>\n    </tr>\n</table>\n</form>\n".toCharArray();
    _jsp_string12 = "\" />\n<input type=\"hidden\" name=\"field_number\" value=\"".toCharArray();
  }
}
