/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import jmk.*;

public class _history__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
// get the history vector from session
Vector history = (Vector)session.getAttribute("sqlHistory");
String type = request.getParameter("type");

if (type != null){
    int hist_rec = -1;
    try{
        hist_rec = Integer.parseInt((String)request.getParameter("hist_rec"));
    }catch(Exception e){}
    if (type.equals("remove")){
        // clear all history
        if (hist_rec < 0){
            history.clear();
        }else{
        // only remove one history record
            history.remove(hist_rec);
        }
    }
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
if (history.size() < 1) out.println("No SQL history.");

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
// show history, descending
for(int i=history.size() -1; i >= 0;i--){
    out.println("<tr class='tb_row_"+(i & 1)+"'>");
    
    out.println("<td>" + i + "</td>");
    out.println("<td><a href='javascript:hist_run("+i+")' title='Execute'><img border=0 src='../images/button_run.png' /></a></td>");
    out.println("<td><a href='javascript:hist_remove("+i+")' title='Remove'><img border=0 src='../images/button_drop.png' /></a></td>");
    out.println("<td><pre>" + history.get(i).toString() + "</pre></td>");
    out.println("</tr>");
}

      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_history__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/history.jsp", 5, 31);
    _caucho_line_map.add(35, 53);
    _caucho_line_map.add(39, 57);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/history.jsp"), "yS/aBzdOjpi462USHE5+Ow==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  static {
    _jsp_string0 = "\n\n\n\n".toCharArray();
    _jsp_string1 = "\n<html>\n<head><title>SQL History</title></head>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n<body>\n<h2>SQL History</h2>\n<hr/>\n".toCharArray();
    _jsp_string3 = "\n</table>\n\n<hr/>\n<input type='button' value='Clear All History' onclick='hist_clear()''/>\n</body>\n</html>\n".toCharArray();
    _jsp_string2 = "\n<table border='0'>\n".toCharArray();
  }
}
