/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import jmk.*;

public class _main__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      out.print(( (String)session.getAttribute("user") ));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( (String)session.getAttribute("db") ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      

// get all tables in the database
ConDB dbcon = (ConDB)session.getAttribute("dbcon");
Connection conn = dbcon.get();
int total_rec = 0;
int total_table = 0;
String sql = "show tables";
PreparedStatement pstm =null;
ResultSet rs =null;
try{
    pstm = conn.prepareStatement(sql);
    rs = pstm.executeQuery();
}catch(SQLException e){out.println(e);}

// count the records of each table
while (rs.next()){
    String curr_tb = rs.getString(1);
    int curr_rec = 0;
    PreparedStatement pstm_rec = null;
    ResultSet rs_rec = null;
    sql = "select count(*) from " + curr_tb;
    
    try{
        pstm_rec = conn.prepareStatement(sql);
        rs_rec = pstm_rec.executeQuery();
    }catch(SQLException e){out.println(e);}
    
    try{
        if(rs_rec.next()){
            curr_rec = rs_rec.getInt(1);
            total_rec += curr_rec;
        }
    }catch(SQLException e){
        out.println(e.getErrorCode() + "---" + e.getSQLState());
    }
    
    total_table++;
    

      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( total_table & 1 ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( curr_tb ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( curr_tb ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( curr_tb ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( curr_tb ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( curr_tb ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( curr_rec ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      

}

      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( total_table ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( total_rec ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print(( session.getAttribute("db") ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_main__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/main.jsp", 14, 30);
    _caucho_line_map.add(14, 32);
    _caucho_line_map.add(22, 34);
    _caucho_line_map.add(62, 75);
    _caucho_line_map.add(63, 77);
    _caucho_line_map.add(67, 79);
    _caucho_line_map.add(68, 81);
    _caucho_line_map.add(69, 83);
    _caucho_line_map.add(70, 85);
    _caucho_line_map.add(74, 87);
    _caucho_line_map.add(83, 96);
    _caucho_line_map.add(92, 98);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/main.jsp"), "AOlUHB8X9qDorKgZ7MCqag==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string6;
  private final static char []_jsp_string11;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string12;
  private final static char []_jsp_string13;
  static {
    _jsp_string4 = "\">\n        <td>".toCharArray();
    _jsp_string7 = "\")'><img border=0  width=18 height=18 src=\"../images/button_properties.png\" alt=\"Properties\"></a></td>\n                    <td><a href='javascript:drop_tb(\"".toCharArray();
    _jsp_string3 = "\n    <tr class=\"tb_row_".toCharArray();
    _jsp_string10 = "</td>\n    </tr>\n".toCharArray();
    _jsp_string6 = "\")'><img border=0 width=18 height=18 src=\"../images/button_browse.png\" alt=\"Browse\"></a></td>\n                    <td><a href='javascript:proper(\"".toCharArray();
    _jsp_string11 = "\n    <tr class=\"tb_header\">\n        <td>".toCharArray();
    _jsp_string5 = "</td>\n        <td>\n            <table>\n                <tr>\n                    <td><a href='javascript:browse(\"".toCharArray();
    _jsp_string1 = "</b> connecting on <b style=\"color:blue\">".toCharArray();
    _jsp_string8 = "\")'><img border=0  width=18 height=18 src=\"../images/button_drop.png\" alt=\"Drop\"></a></td>\n                    <td><a href='javascript:empty_tb(\"".toCharArray();
    _jsp_string2 = "</b></h2>\n<hr/>\n<table border=0>\n    <tr class=\"tb_header\">\n        <td>Table</td>\n        <td>Action</td>\n        <td>Records</td>\n    </tr>\n".toCharArray();
    _jsp_string9 = "\")'><img border=0  width=18 height=18 src=\"../images/button_empty.png\" alt=\"Empty\"></a></td>                    \n                </tr>\n            </table>\n        </td>\n        <td>".toCharArray();
    _jsp_string0 = "\n\n\n\n\n<html>\n<head><title>Home</title></head>\n<body>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n\n<h2>User <b style=\"color:blue\">".toCharArray();
    _jsp_string14 = " :\n    </tr>\n    <tr>\n        <td>Table Name : </td>\n        <td><input type=\"text\" name=\"table\"/></td>\n    </tr>\n    <tr>\n        <td>Fields : </td>\n        <td>\n            <input type=\"text\" name=\"number\" size=\"5\"/>\n            <input type=\"submit\" value=\"Create\">\n        </td>\n    </tr>\n</table>\n</form>\n</body>\n</html>\n".toCharArray();
    _jsp_string12 = " table(s)</td>\n        <td>Sum</td>\n        <td>".toCharArray();
    _jsp_string13 = "</td>\n    </tr>\n</table>\n\n<hr/>\n\n<form action=\"create_table.jsp\" method=\"post\">\n<table>\n    <tr>\n Create table on database ".toCharArray();
  }
}
