/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import jmk.*;

public class _menu__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
//get all tables from database
ConDB dbcon = (ConDB)session.getAttribute("dbcon");
Connection conn = dbcon.get();
Vector vTable = new Vector();
Vector vRec = new Vector();
String sql = "show tables";
int total_table = 0;
PreparedStatement pstm = null;
ResultSet rs = null;
try{
    pstm = conn.prepareStatement(sql);
    rs = pstm.executeQuery();
    while(rs.next()){
        vTable.add(rs.getString(1));
        total_table++;
    }
}catch(SQLException e){ out.println("SQL Error!");}

// count the records of eahc tables
for (int i = 0; i < vTable.size(); i++){
    sql = "select count(*) from " + (String)vTable.get(i);
    try{
        pstm = conn.prepareStatement(sql);
        rs = pstm.executeQuery();
        while(rs.next()){
            vRec.add(rs.getString(1));
        }
    }catch(SQLException e){ out.println("SQL Error!");}
}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( session.getAttribute("db") ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print(( total_table ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      

for (int i = 0; i < vTable.size(); i++){
    String tname = (String)vTable.get(i);
    String rowNum = " (" + (String)vRec.get(i) + " rows)";

      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( tname ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( tname ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( tname ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( rowNum ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
}

      out.write(_jsp_string9, 0, _jsp_string9.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_menu__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/menu.jsp", 14, 31);
    _caucho_line_map.add(45, 63);
    _caucho_line_map.add(45, 65);
    _caucho_line_map.add(50, 67);
    _caucho_line_map.add(58, 74);
    _caucho_line_map.add(63, 76);
    _caucho_line_map.add(63, 78);
    _caucho_line_map.add(66, 80);
    _caucho_line_map.add(69, 82);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/menu.jsp"), "OLfDsw9PoV1vaX4CHDZ0+g==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string2;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string3;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  static {
    _jsp_string0 = "\n\n\n\n<html>\n<head><title>JSP Page</title></head>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n<body>\n<base target=\"_self\">\n\n".toCharArray();
    _jsp_string6 = "\")' title=\"Properties\" target=\"_self\">".toCharArray();
    _jsp_string2 = " (".toCharArray();
    _jsp_string7 = "</a>\n        </td>\n        <td>\n            ".toCharArray();
    _jsp_string9 = "\n</table>\n<hr/>\n<a href=\"create_table.jsp\" target=\"main\">Create Table</a> <br/>\n<a href=\"sql.jsp\" target=\"main\">SQL</a> <br/>\n<a href=\"history.jsp\" target=\"main\">History</a> <br/>\n<hr/>\n<a href=\"javascript:logout()\" target=\"_self\">Logout</a> <br/>\n\n</body>\n</html>\n".toCharArray();
    _jsp_string3 = ")</b><br/>\n<a href=\"menu.jsp\">Refresh</a><br/> \n<a href=\"main.jsp\" target=\"main\">Home</a> <br/>\n<hr/>\n<table cellpadding=0 celspacing=0 style=\"border-collapse: collapse\">\n".toCharArray();
    _jsp_string8 = "\n        </td>\n    <tr/>\n".toCharArray();
    _jsp_string1 = "\nDatabase <b style=''color:green\">".toCharArray();
    _jsp_string4 = "\n    <tr>\n        <td>\n            <a href='javascript:browse(\"".toCharArray();
    _jsp_string5 = "\")'>\n            <img border=0 src=\"../images/button_browse.png\" alt=\"Browse\">\n            </a>\n        </td>\n        <td>\n            <a href='javascript:proper(\"".toCharArray();
  }
}
