/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import jmk.*;

public class _mod_0field__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String table = request.getParameter("table");
String field = request.getParameter("field");

if (table != null && field != null){
    
    String fname = "";
    String ftype = "";
    String fsize = "";
    String fdefault = "";
    
    // Hashing for the pull down menus
    Map typeSel = new HashMap();
    typeSel.put("VARCHAR", "");
    typeSel.put("TEXT", "");
    typeSel.put("DATE", "");
    typeSel.put("SMALLINT", "");
    typeSel.put("MEDIUMINT", "");
    typeSel.put("INT", "");
    typeSel.put("BIGINT", "");
    typeSel.put("DOUBLE", "");
    typeSel.put("DECIMAL", "");
    typeSel.put("DATETIME", "");
    typeSel.put("TIMESTAMP", "");
    typeSel.put("TIME", "");
    typeSel.put("YEAR", "");
    typeSel.put("CHAR", "");
    typeSel.put("TINYBLOB", "");
    typeSel.put("TINYTEXT", "");
    typeSel.put("BLOB", "");
    typeSel.put("MEDIUMBLOB", "");
    typeSel.put("MEDIUMTEXT", "");
    typeSel.put("LONGBOLB", "");
    typeSel.put("LONGTEXT", "");
    typeSel.put("ENUM", "");
    typeSel.put("SET", "");
    typeSel.put("FLOAT", "");
    typeSel.put("TINYINT", "");

    // get DB connection
    ConDB dbcon = (ConDB)session.getAttribute("dbcon");
    Connection conn = dbcon.get();
    String sql = "desc `" +table+ "`";
    PreparedStatement pstm = null;
    ResultSet rs = null;
    try{
        pstm = conn.prepareStatement(sql);
        rs = pstm.executeQuery();
        // get the field name, data type, length, default ...
        while (rs.next()){
            if(rs.getString(1).equals(field)){
                fname = rs.getString(1);
                fdefault = rs.getString(5);
                String temp = rs.getString(2).toUpperCase();
                if (temp.indexOf("(") < 0){
                    ftype = temp;
                }else{
                    ftype = temp.substring(0, temp.indexOf("("));
                    fsize = temp.substring(temp.indexOf("(")+1, temp.indexOf(")"));
                }
                // HASH the null value
                if (rs.getString(3).equals("YES")){
                    typeSel.put("NULL", "selected");
                    typeSel.put("NOT NULL", "");
                }else{
                    typeSel.put("NULL", "");
                    typeSel.put("NOT NULL", "selected");
                }
                if (rs.getString(6).equals("auto_increment")){
                    typeSel.put("AUTO_INCREMENT", "selected");
                    typeSel.put("NO_ATI", "");
                }else{
                    typeSel.put("AUTO_INCREMENT", "");
                    typeSel.put("NO_ATI", "selected");
                }

                // reHASH the field type
                typeSel.remove(ftype);
                typeSel.put(ftype, "selected");
                break;
            }
        }
    }catch(SQLException e){out.println(e);}

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( field ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print(( table ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( fname ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( (String)typeSel.get("VARCHAR") ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( (String)typeSel.get("TEXT") ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( (String)typeSel.get("DATE") ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( (String)typeSel.get("SMALLINT") ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( (String)typeSel.get("MEDIUMINT") ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( (String)typeSel.get("INT") ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( (String)typeSel.get("BIGINT") ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( (String)typeSel.get("DOUBLE") ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( (String)typeSel.get("DECIMAL") ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print(( (String)typeSel.get("DATETIME") ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print(( (String)typeSel.get("TIMESTAMP") ));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print(( (String)typeSel.get("TIME") ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print(( (String)typeSel.get("YEAR") ));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print(( (String)typeSel.get("CHAR") ));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print(( (String)typeSel.get("TINYBLOB") ));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( (String)typeSel.get("TINYTEXT") ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print(( (String)typeSel.get("BLOB") ));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print(( (String)typeSel.get("MEDIUMBLOB") ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print(( (String)typeSel.get("MEDIUMTEXT") ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print(( (String)typeSel.get("LONGBOLB") ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print(( (String)typeSel.get("LONGTEXT") ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(( (String)typeSel.get("ENUM") ));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print(( (String)typeSel.get("SET") ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print(( (String)typeSel.get("FLOAT") ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print(( (String)typeSel.get("TINYINT") ));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      out.print(( fsize ));
      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print(( (String)typeSel.get("NOT NULL") ));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print(( (String)typeSel.get("NULL") ));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      out.print(( fdefault ));
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print(( (String)typeSel.get("NO_ATI") ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      out.print(( (String)typeSel.get("AUTO_INCREMENT") ));
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print(( field ));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print(( table ));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      
}else{
    out.println("Error!");
}

      out.write(_jsp_string38, 0, _jsp_string38.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_mod_0field__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/mod_field.jsp", 12, 31);
    _caucho_line_map.add(97, 116);
    _caucho_line_map.add(97, 118);
    _caucho_line_map.add(112, 120);
    _caucho_line_map.add(114, 122);
    _caucho_line_map.add(115, 124);
    _caucho_line_map.add(116, 126);
    _caucho_line_map.add(117, 128);
    _caucho_line_map.add(118, 130);
    _caucho_line_map.add(119, 132);
    _caucho_line_map.add(120, 134);
    _caucho_line_map.add(121, 136);
    _caucho_line_map.add(122, 138);
    _caucho_line_map.add(123, 140);
    _caucho_line_map.add(124, 142);
    _caucho_line_map.add(125, 144);
    _caucho_line_map.add(126, 146);
    _caucho_line_map.add(127, 148);
    _caucho_line_map.add(128, 150);
    _caucho_line_map.add(129, 152);
    _caucho_line_map.add(130, 154);
    _caucho_line_map.add(131, 156);
    _caucho_line_map.add(132, 158);
    _caucho_line_map.add(133, 160);
    _caucho_line_map.add(134, 162);
    _caucho_line_map.add(135, 164);
    _caucho_line_map.add(136, 166);
    _caucho_line_map.add(137, 168);
    _caucho_line_map.add(138, 170);
    _caucho_line_map.add(142, 174);
    _caucho_line_map.add(143, 176);
    _caucho_line_map.add(145, 178);
    _caucho_line_map.add(148, 180);
    _caucho_line_map.add(149, 182);
    _caucho_line_map.add(156, 184);
    _caucho_line_map.add(157, 186);
    _caucho_line_map.add(174, 188);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/mod_field.jsp"), "06T793WzQACVE3dypdQf0A==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string35;
  private final static char []_jsp_string16;
  private final static char []_jsp_string7;
  private final static char []_jsp_string30;
  private final static char []_jsp_string11;
  private final static char []_jsp_string32;
  private final static char []_jsp_string38;
  private final static char []_jsp_string36;
  private final static char []_jsp_string13;
  private final static char []_jsp_string5;
  private final static char []_jsp_string19;
  private final static char []_jsp_string21;
  private final static char []_jsp_string37;
  private final static char []_jsp_string3;
  private final static char []_jsp_string34;
  private final static char []_jsp_string27;
  private final static char []_jsp_string31;
  private final static char []_jsp_string15;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string8;
  private final static char []_jsp_string25;
  private final static char []_jsp_string6;
  private final static char []_jsp_string20;
  private final static char []_jsp_string33;
  private final static char []_jsp_string12;
  private final static char []_jsp_string22;
  private final static char []_jsp_string10;
  private final static char []_jsp_string18;
  private final static char []_jsp_string14;
  private final static char []_jsp_string17;
  private final static char []_jsp_string29;
  private final static char []_jsp_string2;
  private final static char []_jsp_string24;
  private final static char []_jsp_string26;
  private final static char []_jsp_string23;
  private final static char []_jsp_string0;
  private final static char []_jsp_string28;
  private final static char []_jsp_string1;
  static {
    _jsp_string35 = " value=\"AUTO_INCREMENT\">AUTO_INCREMENT</option>\n    </select>\n  </tr>\n</table>\n\n<br/><br/>\n<input type=\"hidden\" name=\"type\" value=\"mod_field\" />\n<input type=\"hidden\" name=\"field\" value=\"".toCharArray();
    _jsp_string16 = " value=\"TIME\">TIME</option>\n    <option ".toCharArray();
    _jsp_string7 = " value=\"DATE\">DATE</option>\n    <option ".toCharArray();
    _jsp_string30 = "\"></td>\n    <td ><select size=\"1\" name=\"null_value\">\n    <option ".toCharArray();
    _jsp_string11 = " value=\"BIGINT\">BIGINT</option>\n    <option ".toCharArray();
    _jsp_string32 = " value=\"NULL\">null</option>\n    </select></td>\n    <td ><input type=\"text\" name=\"default_value\" value=\"".toCharArray();
    _jsp_string38 = "\n</body>\n</html>\n".toCharArray();
    _jsp_string36 = "\" />\n<input type=\"hidden\" name=\"table\" value=\"".toCharArray();
    _jsp_string13 = " value=\"DECIMAL\">DECIMAL</option>\n    <option ".toCharArray();
    _jsp_string5 = " value=\"VARCHAR\">VARCHAR</option>\n    <option ".toCharArray();
    _jsp_string19 = " value=\"TINYBLOB\">TINYBLOB</option>\n    <option ".toCharArray();
    _jsp_string21 = " value=\"BLOB\">BLOB</option>\n    <option ".toCharArray();
    _jsp_string37 = "\" />\n\n<input type=\"submit\" value=\"Modify\" />\n</form>\n\n<table border=\"0\" width=\"100%\">\n<tr><td>\n*  If field type is \"enum\" or \"set\", please enter the values using this format: 'a','b','c'...\n</td></tr>\n<tr><td>\nIf you ever need to put a backslash (\"\\\") or a single quote (\"'\") amongst those values, backslashes it (for example '\\\\xyz' or 'a\\'b').  \n</td></tr>\n<tr><td>\n**  For default values, please enter just a single value, without backslash escaping or quotes, using this format: a  \n</td></tr>\n</table>\n\n".toCharArray();
    _jsp_string3 = "</b></h2>\n<hr/>\n<form action=\"run_sql.jsp\" method=\"post\">\n<table border=\"1\">\n  <tr>\n    <td >Field Name</td>\n    <td >Type</td>\n    <td >Length</td>\n    <td >Null</td>\n    <td >Default</td>\n    <td >Extra</td>\n  </tr>\n\n  <!-- use the HASH function to put the \"SELECTED\" key word to the options -->\n  <tr>\n    <td ><input type=\"text\" name=\"field_name\" size=\"16\" value=\"".toCharArray();
    _jsp_string34 = " value=\"\"></option>\n    <option ".toCharArray();
    _jsp_string27 = " value=\"SET\">SET</option>\n    <option ".toCharArray();
    _jsp_string31 = " value=\"NOT NULL\">not null</option>\n    <option ".toCharArray();
    _jsp_string15 = " value=\"TIMESTAMP\">TIMESTAMP</option>\n    <option ".toCharArray();
    _jsp_string4 = "\"></td>\n    <td ><select size=\"1\" name=\"data_type\">\n    <option ".toCharArray();
    _jsp_string9 = " value=\"MEDIUMINT\">MEDIUMINT</option>\n    <option ".toCharArray();
    _jsp_string8 = " value=\"SMALLINT\">SMALLINT</option>\n    <option ".toCharArray();
    _jsp_string25 = " value=\"LONGTEXT\">LONGTEXT</option>\n    <option ".toCharArray();
    _jsp_string6 = " value=\"TEXT\">TEXT</option>\n    <option ".toCharArray();
    _jsp_string20 = " value=\"TINYTEXT\">TINYTEXT</option>\n    <option ".toCharArray();
    _jsp_string33 = "\" size=\"10\"></td>\n    \n    <td ><select size=\"1\" name=\"extra\">\n    <option ".toCharArray();
    _jsp_string12 = " value=\"DOUBLE\">DOUBLE</option>\n    <option ".toCharArray();
    _jsp_string22 = " value=\"MEDIUMBLOB\">MEDIUMBLOB</option>\n    <option ".toCharArray();
    _jsp_string10 = " value=\"INT\">INT</option>\n    <option ".toCharArray();
    _jsp_string18 = " value=\"CHAR\">CHAR</option>\n    <option ".toCharArray();
    _jsp_string14 = " value=\"DATETIME\">DATETIME</option>\n    <option ".toCharArray();
    _jsp_string17 = " value=\"YEAR\">YEAR</option>\n    <option ".toCharArray();
    _jsp_string29 = " value=\"TINYINT\">TINYINT</option>\n    </select></td>\n    <td ><input type=\"text\" name=\"data_length\" size=\"5\" value=\"".toCharArray();
    _jsp_string2 = "</b> in <b style=\"color:blue\">".toCharArray();
    _jsp_string24 = " value=\"LONGBOLB\">LONGBOLB</option>\n    <option ".toCharArray();
    _jsp_string26 = " value=\"ENUM\">ENUM</option>\n    <option ".toCharArray();
    _jsp_string23 = " value=\"MEDIUMTEXT\">MEDIUMTEXT</option>\n    <option ".toCharArray();
    _jsp_string0 = "\n\n\n\n<html>\n<head><title>Create Table</title></head>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n<body>\n".toCharArray();
    _jsp_string28 = " value=\"FLOAT\">FLOAT</option>\n    <option ".toCharArray();
    _jsp_string1 = "\n\n<h2>Modify Field <b style=\"color:blue\">".toCharArray();
  }
}
