/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp._myadmin;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import jmk.*;

public class _show_0table__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
String table = request.getParameter("table");

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print(( table));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print(( table ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( table ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( table ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( table ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      

int recCount = 0;
Vector vField = new Vector();

ConDB dbcon = (ConDB)session.getAttribute("dbcon");
Connection conn = dbcon.get();
String sql = "desc " + table;
PreparedStatement pstm = null;
ResultSet rs = null;
// show table structure
try{
    pstm = conn.prepareStatement(sql);
    rs = pstm.executeQuery();

    while(rs.next()){

        String Field = rs.getString(1);
        vField.add(Field);
        String Type = rs.getString(2);
        String Null = rs.getString(3);
        String Key = rs.getString(4);
        String Default = rs.getString(5);
        String Extra = rs.getString(6);
        recCount++;

      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( recCount & 1 ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( Field ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( Type ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( Null ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( Key ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( Default ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( Extra ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( table ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( Field ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( table ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( Field ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print(( table ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( Field ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print(( table ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( Field ));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print(( table ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( Field ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      
    }
}catch(SQLException e){out.println("SQL Error!");}

      out.write(_jsp_string17, 0, _jsp_string17.length);
      
    sql = "show index from " + table;
    MyConstraint mc = new MyConstraint();
    try{
        pstm = conn.prepareStatement(sql);
        rs = pstm.executeQuery();
        
        while (rs.next()){        
            // put the data to MyConstraint, which can read the index type
            mc.add(rs.getString(2).charAt(0),rs.getString(3),rs.getString(5));
        }
    }catch(SQLException e){ out.println("SQL Error!");}
    Vector pk = mc.getPk();
    Vector uk = mc.getUk();
    Vector idx = mc.getIdx();
    
    if(mc.size() > 0){
        int styleCount = 0;

      out.write(_jsp_string18, 0, _jsp_string18.length);
      
        // Primary key start
        if(pk.size() > 0){

      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( (styleCount & 1) ));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( table ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      
    for(int i=0; i < pk.size(); i++){
        out.println("<tr><td>"+pk.get(i).toString()+"</td></tr>");
    }

      out.write(_jsp_string21, 0, _jsp_string21.length);
      
        styleCount++;
        // Primary key end
        }

      out.write(_jsp_string22, 0, _jsp_string22.length);
      
        // Unique start
        for(int i=0; i < uk.size(); i++, styleCount++){
            MyIndex mi = (MyIndex)uk.get(i);
            Vector ukField = mi.getField();

      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( (styleCount & 1) ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( mi.getKeyName() ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print(( table ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print(( mi.getKeyName() ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      
    for(int j=0; j < ukField.size(); j++){
        out.println("<tr><td>"+ukField.get(j).toString()+"</td></tr>");
    }

      out.write(_jsp_string21, 0, _jsp_string21.length);
      
        // Unique end
        }

      out.write(_jsp_string22, 0, _jsp_string22.length);
      
        // Index start
        for(int i=0; i < idx.size(); i++, styleCount++){
            MyIndex mi = (MyIndex)idx.get(i);
            Vector idxField = mi.getField();

      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( (styleCount & 1) ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( mi.getKeyName() ));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print(( table ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print(( mi.getKeyName() ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      
    for(int j=0; j < idxField.size(); j++){
        out.println("<tr><td>"+idxField.get(j).toString()+"</td></tr>");
    }

      out.write(_jsp_string21, 0, _jsp_string21.length);
      
        // Index end
        }

      out.write(_jsp_string27, 0, _jsp_string27.length);
      
    }

      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print(( table ));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      
    for(int i=0; i<vField.size(); i++){
        String fd = (String)vField.get(i);

      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print(( fd ));
      out.write(_jsp_string31, 0, _jsp_string31.length);
      out.print(( fd ));
      out.write(_jsp_string32, 0, _jsp_string32.length);
      
    }

      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print(( table ));
      out.write(_jsp_string34, 0, _jsp_string34.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_show_0table__jsp.java", "foo");
    _caucho_line_map.add("/myadmin/show_table.jsp", 5, 31);
    _caucho_line_map.add(17, 35);
    _caucho_line_map.add(21, 37);
    _caucho_line_map.add(22, 39);
    _caucho_line_map.add(23, 41);
    _caucho_line_map.add(24, 43);
    _caucho_line_map.add(39, 45);
    _caucho_line_map.add(65, 72);
    _caucho_line_map.add(66, 74);
    _caucho_line_map.add(67, 76);
    _caucho_line_map.add(68, 78);
    _caucho_line_map.add(69, 80);
    _caucho_line_map.add(70, 82);
    _caucho_line_map.add(71, 84);
    _caucho_line_map.add(75, 86);
    _caucho_line_map.add(75, 88);
    _caucho_line_map.add(76, 90);
    _caucho_line_map.add(76, 92);
    _caucho_line_map.add(77, 94);
    _caucho_line_map.add(77, 96);
    _caucho_line_map.add(78, 98);
    _caucho_line_map.add(78, 100);
    _caucho_line_map.add(79, 102);
    _caucho_line_map.add(79, 104);
    _caucho_line_map.add(85, 106);
    _caucho_line_map.add(92, 111);
    _caucho_line_map.add(119, 131);
    _caucho_line_map.add(123, 136);
    _caucho_line_map.add(127, 138);
    _caucho_line_map.add(133, 140);
    _caucho_line_map.add(141, 146);
    _caucho_line_map.add(147, 152);
    _caucho_line_map.add(153, 159);
    _caucho_line_map.add(154, 161);
    _caucho_line_map.add(157, 163);
    _caucho_line_map.add(157, 165);
    _caucho_line_map.add(163, 167);
    _caucho_line_map.add(171, 173);
    _caucho_line_map.add(176, 178);
    _caucho_line_map.add(182, 185);
    _caucho_line_map.add(183, 187);
    _caucho_line_map.add(186, 189);
    _caucho_line_map.add(186, 191);
    _caucho_line_map.add(192, 193);
    _caucho_line_map.add(200, 199);
    _caucho_line_map.add(205, 204);
    _caucho_line_map.add(211, 208);
    _caucho_line_map.add(222, 210);
    _caucho_line_map.add(226, 215);
    _caucho_line_map.add(226, 217);
    _caucho_line_map.add(227, 219);
    _caucho_line_map.add(237, 223);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("myadmin/show_table.jsp"), "lfAqtA3B8cR0nPYjvQZ0Zg==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string34;
  private final static char []_jsp_string19;
  private final static char []_jsp_string18;
  private final static char []_jsp_string24;
  private final static char []_jsp_string20;
  private final static char []_jsp_string17;
  private final static char []_jsp_string15;
  private final static char []_jsp_string4;
  private final static char []_jsp_string25;
  private final static char []_jsp_string33;
  private final static char []_jsp_string13;
  private final static char []_jsp_string28;
  private final static char []_jsp_string32;
  private final static char []_jsp_string5;
  private final static char []_jsp_string23;
  private final static char []_jsp_string27;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  private final static char []_jsp_string22;
  private final static char []_jsp_string31;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string11;
  private final static char []_jsp_string26;
  private final static char []_jsp_string1;
  private final static char []_jsp_string9;
  private final static char []_jsp_string6;
  private final static char []_jsp_string14;
  private final static char []_jsp_string21;
  private final static char []_jsp_string12;
  private final static char []_jsp_string29;
  private final static char []_jsp_string30;
  private final static char []_jsp_string16;
  static {
    _jsp_string0 = "\n\n\n\n".toCharArray();
    _jsp_string7 = "\n    <tr class=\"tb_row_".toCharArray();
    _jsp_string34 = "\"/>\n        Create an index on <input type=\"text\" name=\"number\" value=\"1\" size=\"5\"/> columns <input type=\"submit\" value=\"Go\"/>\n</form>\n</body>\n</html>\n\n".toCharArray();
    _jsp_string19 = "\">\n        <td>PRIMARY</td>\n        <td>PRIMARY</td>\n        <td>\n            <a href='javascript:drop_key(\"".toCharArray();
    _jsp_string18 = "\n<table>\n    <tr>Index table :</tr>\n    <tr class=\"tb_header\">\n        <td>Keyname</td>\n        <td>Type</td>\n        <td>Action</td>\n        <td>Field</td>\n    </tr>\n".toCharArray();
    _jsp_string24 = "\",\"".toCharArray();
    _jsp_string20 = "\",\"PRIMARY\")'>\n                <img border=0 width=18 height=18 src=\"../images/button_drop.png\">\n            </a>\n        </td>\n        <td>\n            <table>\n".toCharArray();
    _jsp_string17 = "\n</table>\n<br/>\n<!-- Index Table -->\n".toCharArray();
    _jsp_string15 = "\")' title=\"Index\"><img border=0  width=18 height=18 src=\"../images/button_index.png\" /></a></td>                    \n                    <td><a href='javascript:new_uni(\"".toCharArray();
    _jsp_string4 = "\")'>Browse</a></td>\n        <td width=\"25%\" align=\"center\"><a href='javascript:empty_tb(\"".toCharArray();
    _jsp_string25 = "\")'>\n                <img border=0 width=18 height=18 src=\"../images/button_drop.png\">\n            </a>\n        </td>\n        <td>\n            <table>\n".toCharArray();
    _jsp_string33 = "\n                </select>\n            </td>\n            <td><input type=\"submit\" value=\"Go\"</td>\n        </tr>\n   </table>\n</form>\n<form action=\"create_index.jsp\" method=\"post\">\n        <input type=\"hidden\" name=\"table\" value=\"".toCharArray();
    _jsp_string13 = "\")' title=\"Drop\"><img border=0  width=18 height=18 src=\"../images/button_drop.png\" /></a></td>\n                    <td><a href='javascript:new_pk(\"".toCharArray();
    _jsp_string28 = "\n\n<hr/>\n<form action=\"add_field.jsp\" method=\"post\">\n<input type=\"hidden\" name=\"table\" value=\"".toCharArray();
    _jsp_string32 = "</option>\n".toCharArray();
    _jsp_string5 = "\")'>Empty</a></td>\n        <td width=\"25%\" align=\"center\"><a href='javascript:drop_tb(\"".toCharArray();
    _jsp_string23 = "</td>\n        <td>UNIQUE</td>\n        <td>\n            <a href='javascript:drop_key(\"".toCharArray();
    _jsp_string27 = "\n</table>\n".toCharArray();
    _jsp_string2 = "</b></h2>\n<hr/>\n<table border=\"0\" width=\"100%\">\n    <tr>\n        <td width=\"25%\" align=\"center\"><a href='javascript:proper(\"".toCharArray();
    _jsp_string8 = "\">\n        <td>".toCharArray();
    _jsp_string22 = "\n\n".toCharArray();
    _jsp_string31 = "\">After ".toCharArray();
    _jsp_string3 = "\")'>Structure</a></td>\n        <td width=\"25%\" align=\"center\"><a href='javascript:browse(\"".toCharArray();
    _jsp_string10 = "&nbsp;</td>\n        <td>\n            <table>\n                <tr>\n                    <td><a href='javascript:mod_fd(\"".toCharArray();
    _jsp_string11 = "\", \"".toCharArray();
    _jsp_string26 = "</td>\n        <td>INDEX</td>\n        <td>\n            <a href='javascript:drop_key(\"".toCharArray();
    _jsp_string1 = "\n<html>\n<head><title>Show Table</title></head>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mystyle.css\" />\n<script src=\"../js/sql.js\"></script>\n<!-- import ended -->\n\n\n<body>\n<h2>Table <b style=\"color:blue\">".toCharArray();
    _jsp_string9 = "&nbsp;</td>\n        <td>".toCharArray();
    _jsp_string6 = "\")'>Drop</a></td>\n    </tr>\n</table>\n<hr/>\n<table border=\"0\" align=\"center\">\n    <tr>Structure table :</tr>\n    <tr class=\"tb_header\">\n        <td>Field</td>\n        <td>Type</td>\n        <td>Null</td>\n        <td>Key</td>\n        <td>Default</td>\n        <td>Extra</td>\n        <td>Action</td>\n    </tr>\n".toCharArray();
    _jsp_string14 = "\")' title=\"Primary\"><img border=0  width=18 height=18 src=\"../images/button_primary.png\" /></a></td>\n                    <td><a href='javascript:new_idx(\"".toCharArray();
    _jsp_string21 = "\n            </table>\n        </td>\n    </tr>\n".toCharArray();
    _jsp_string12 = "\")' title=\"Modify\"><img border=0  width=18 height=18 src=\"../images/button_edit.png\" /></a></td>\n                    <td><a href='javascript:drop_fd(\"".toCharArray();
    _jsp_string29 = "\"/>\n    <table>\n        <tr>\n            <td>Add new field : </td>\n    \n            <td><input type=\"text\" name=\"number\" value=\"1\" size=\"5\" /></td>\n\n            <td>\n                <select size=\"1\" name=\"after\">\n                    <option selected value=\"--end--\">At End of Table</option>\n                    <option value=\"--first--\">At Beginning of Table</option>\n".toCharArray();
    _jsp_string30 = "\n                    <option value=\"".toCharArray();
    _jsp_string16 = "\")' title=\"Unique\"><img border=0  width=18 height=18 src=\"../images/button_unique.png\" /></a></td>   \n                </tr>\n            </table>\n        </td>\n    </tr>\n\n".toCharArray();
  }
}
