/*
 * JSP generated by Resin-3.0.s041002 (built Sat, 02 Oct 2004 04:47:31 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import java.io.*;
import jmk.*;

public class _auth__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, "/error.jsp", session, 8192, true);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
// read config setting from config.ini
    String jdbc = "com.mysql.jdbc.Driver";  // default JDBC driver
    String configFile = application.getRealPath("/")+"/WEB-INF/config.ini"; // config.ini location
    String mode = (String)request.getParameter("mode"); // login mode
    String ip = (String)request.getRemoteAddr();    // remote IP
    Properties pp = new Properties();
    FileInputStream fi = null;
    try{
        fi = new FileInputStream(configFile);
        pp.load(fi);
    }catch(FileNotFoundException e){
        out.println(e);
    }catch(IOException e){
        out.println(e);
    }
    jdbc = pp.getProperty("jdbc");
    
    // change session time
    int sessTime = 300;
    try{
        sessTime = Integer.parseInt(pp.getProperty("session")) * 60;
    }catch(Exception e){}
    session.setMaxInactiveInterval(sessTime);

// users data
String host = (String)request.getParameter("host");
String port = (String)request.getParameter("port");
String db = (String)request.getParameter("database");
String user = (String)request.getParameter("user");
String pass = (String)request.getParameter("password");

// System Admin data
if(mode != null && mode.equals("admin") && ip.equals("127.0.0.1")){
    host = pp.getProperty("host");
    port = pp.getProperty("port");
    db = pp.getProperty("db");
    user = pp.getProperty("user");
    pass = pp.getProperty("pass");
}else{
    mode = "outer user";
}
    ConDB dbcon = new ConDB(jdbc);
    session.setAttribute("dbcon", dbcon);
    
if (dbcon.open(host,port,db, user, pass)){
    // set a login = "Y" for login
    session.setAttribute("login", "Y");
    session.setAttribute("user", user);
    session.setAttribute("db", db);
    session.setAttribute("sqlHistory", new Vector());
    System.out.println("==== Login ====");
    System.out.println("Date  : " + new java.util.Date() );
    System.out.println("IP    : " + ip );
    System.out.println("Mode  : " + mode );
    System.out.println("DB    : " + db );
    System.out.println("User  : " + user );

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
}else{
    session.invalidate();

      out.write(_jsp_string2, 0, _jsp_string2.length);
      
}

      out.write(_jsp_string3, 0, _jsp_string3.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -1589519462977561320L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    _caucho_line_map = new com.caucho.java.LineMap("_auth__jsp.java", "foo");
    _caucho_line_map.add("/auth.jsp", 6, 32);
    _caucho_line_map.add(83, 91);
    _caucho_line_map.add(96, 96);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("auth.jsp"), "fd0FqAcrza7W8KkDRSkHqg==", false);
    _caucho_depends.add(depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  static {
    _jsp_string2 = "\n<html>\n<!-- import the CSS & JavaScript -->\n<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/mystyle.css\" />\n<script src=\"./js/sql.js\"></script>\n<!-- import ended -->\n<h2 align=\"center\">Login failed!</h2>\n<h2 align=\"center\">Please try again!</h2>\n<h2 align=\"center\"><a href=\"login.jsp\">Login</a></h2>\n</html>\n".toCharArray();
    _jsp_string0 = "\n\n\n\n\n".toCharArray();
    _jsp_string1 = "\n<html>\n\n<head>\n<title>jspMyAdmin</title>\n</head>\n\n<frameset cols=\"200,*\">\n  <frame name=\"menu\" src=\"./myadmin/menu.jsp\" target=\"main\">\n  <frame name=\"main\" src=\"./myadmin/main.jsp\">\n  <noframes>\n  <body>\n\n  <p>This page uses frames, but your browser doesn't support them.</p>\n\n  </body>\n  </noframes>\n</frameset>\n\n</html>\n".toCharArray();
    _jsp_string3 = "\n\n\n".toCharArray();
  }
}
